### ISSUE TITLE
do not list "want" versions for "other" modules

### ISSUE THREAD

**Issue by karenetheridge** [dagolden/Dist-Zilla-Plugin-Test-ReportPrereqs#24]
in test output, I see this:

```
# === Other Modules ===
# 
#     Module                Want     Have
#     --------------------- ---- --------
#     CPAN::Meta::Validator  any 2.143240
#     Cpanel::JSON::XS       any  missing
#     JSON::PP               any  2.27300
#     JSON::XS               any     2.33
```

There isn't actually any wanted version for these - we just want to know what is installed - so the "Want" column should be omitted entirely.

**Comment by dagolden** [comment]
I think that's for formatting consistency.  I'd be OK with it saying N/A
instead of any, though.

**Comment by karenetheridge** [comment]
There already isn't any consistency since the column widths of each section are different :)
