### ISSUE TITLE
print noisy warning when a static source is incorrectly used

### ISSUE THREAD

**Issue by karenetheridge** [dagolden/Dist-Zilla-Plugin-Test-ReportPrereqs#30]
I might send a patch for this later, but I'm creating an issue now so it's not lost:

When META.\* is used as the data source for a distribution using `dynamic_config => 1`, rather than MYMETA.*, this should be called out as a warning in the test output, just as required-but-missing prereqs are also pointed out using a noisy warning.

e.g. this report: http://www.cpantesters.org/cpan/report/9584f7d0-3f0f-11e6-9fc5-14bfbd15da07
shows that a static source was used, because MYMETA.json doesn't exist -- this indicates a tooling error on the user's side, because MYMETA.json ought to have been created by Makefile.PL. (and it's this lack of reading dynamic prereqs that caused all the remaining failures in this report.)

**Comment by karenetheridge** [comment]
Here's my first draft:

{{{
diff --git a/lib/Dist/Zilla/Plugin/Test/ReportPrereqs.pm b/lib/Dist/Zilla/Plugin/Test/ReportPrereqs.pm
index 3c32af8..902ae4a 100644
--- a/lib/Dist/Zilla/Plugin/Test/ReportPrereqs.pm
+++ b/lib/Dist/Zilla/Plugin/Test/ReportPrereqs.pm
@@ -295,12 +295,14 @@ my $full_prereqs = _merge_prereqs(
 
 # Add dynamic prereqs to the included modules list (if we can)
 my ($source) = grep { -f } 'MYMETA.json', 'MYMETA.yml';
+my $cpan_meta_error;
 if ( $source && $HAS_CPAN_META
     && (my $meta = eval { CPAN::Meta->load_file($source) } )
 ) {
     $full_prereqs = _merge_prereqs($full_prereqs, $meta->prereqs);
 }
 else {
+    $cpan_meta_error = $@;    # capture error from CPAN::Meta->load_file($source)
     $source = 'static metadata';
 }
 
@@ -386,6 +388,15 @@ if ( @full_reports ) {
     diag "\nVersions for all modules listed in $source (including optional ones):\n\n", @full_reports;
 }
 
+if ($source eq 'static metadata' and $cpan_meta_error) {
+    my ($orig_source) = grep { -f } 'MYMETA.json', 'MYMETA.yml';
+    diag join("\n",
+        "\n*** WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING ***\n",
+        "CPAN::Meta->load_file('$orig_source') failed with: $cpan_meta_error\n",
+        "\n"
+    );
+}
+
 if ( @dep_errors ) {
     diag join("\n",
         "\n*** WARNING WARNING WARNING WARNING WARNING WARNING WARNING WARNING ***\n",
}}}

**Comment by xdg** [comment]
I think the "WARNING" repeat is unnecessary, but I'm OK with it otherwise.  PR it?
