### ISSUE TITLE
need some mechanism for including arbitrary code execution in the test

### ISSUE THREAD

**Issue by karenetheridge** [dagolden/Dist-Zilla-Plugin-Test-ReportPrereqs#34]
I've been seeing a few tickets lately that look like this --

That code is using JSON::MaybeXS, so the problem is not in the distribution directly, but somewhere upstream in a JSON serializer. There's some sort of compatibility issue bubbling around between the JSON modules, but how can this be reported?  it would be ideal if one could include (in t/00-report-preereqs.t) the installed version of whatever `JSON::MaybeXS::JSON()` evaluates to -- since this is not a static module name, we need to add special support for this to get it to come out right when the test is executed.

I'm thinking of maybe doing something evil like embedding a coderef into the .dd file, so it gets evaluated correctly when the .dd file is read back in, but maybe there's a better way.

**Comment by xdg** [comment]
Nit: I don't see an example when you say "like this" so I'm replying in general.  :-)

I don't understand why this isn't something that can be handled via `include`.  I.e. to report the individual things that JSON::MaybeXS could be delegating to.  If listing those all the time is annoying, I'd be open to considering an "auto_include" feature that drops a predefined list of modules into `include` whenever a known module multiplexer is in the prereqs.  I expect the list of such modules to be small-ish and easy to custom curate.

I don't want to run arbitrary code in .dd files.  I might be willing to predefine some evaluation code to run for specific modules.

However, I don't think that running `JSON::MaybeXS::JSON()` actually helps diagnose a problem, as the JSON module selection depends on what's already loaded and that will be different in the failing test code than in the prereq reporting code.

So my inclination so far is "won't fix" except for being open to adding an "auto_include" feature to make life easy for common annoying cases.

**Comment by karenetheridge** [comment]
> I've been seeing a few tickets lately that look like this --

gah, it looks like I meant to paste something and never noticed that that failed. Unfortunately I cannot remember what the issue was :(  Something to do with weird JSON decoding I guess...  But you're right that JSON::MaybeXS changes its behaviour depending on whether JSON::XS is already loaded, so printing the `JSON()` result could be inaccurate.

I'll close this for now as I can't think of another (reasonable) example for code injection.
